image: debian/buster
repositories:
packages:
  - apt-transport-https
  - rsync
  - wget
sources:
  - hg+ssh://hg@hg.sr.ht/~ociaw/RandN
secrets:
  - 46cc09d6-0cd1-4bf1-8561-d383aeacd02c
  - 5064e082-44e8-482c-821f-ef9864647c0d
  - 5ef6e0f9-b383-48e2-aa30-5277115e03e2
  - 358cb8db-8be2-45a7-bc5e-86c4e1728e43
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_ROOT: /opt/dotnet
tasks:
  - setup: |
      cd ./RandN
      bookmark=$(hg log --template "{bookmarks}" -r ".")
      pattern="^v[0-9].*$"
      if [[ ! ${bookmark} =~ ${pattern} ]] && [[ ! $bookmark = "master" ]]
      then
          echo "Exiting due to non-master or non-versioned bookmark: $bookmark"
          complete-build
      fi
      cd ~
      wget -O- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
      sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
      wget https://packages.microsoft.com/config/debian/10/prod.list
      sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
      sudo apt-get update
      sudo apt-get install dotnet-sdk-2.1 -y
      dotnet tool install -v minimal -g Wyam.Tool
  - build: |
      export PATH="$PATH:/home/build/.dotnet/tools"
      cd RandN/docs
      bookmark=$(hg log --template "{bookmarks}" -r ".")
      if [[ $bookmark = "master" ]]
      then
          echo "Bookmark '$bookmark' does not need a different link root:"
          bookmark=''
      fi
      wyam build --setting "LinkRoot=$bookmark"
  - deploy: |
      cd RandN/docs
      bookmark=$(hg log --template "{bookmarks}" -r ".")
      if [ -z $bookmark ]
      then
          echo "Empty bookmark, aborting."
          exit 1
      fi
      ssh webserver mkdir -p /var/randn/$bookmark/
      rsync -rqz ./output/ webserver:/var/randn/$bookmark/
